version: '3.8'

services:
  odoo:
    image: odoo:18.0
    container_name: odoo18.2
    depends_on:
      - db
    ports:
      - "8090:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons

  db:
    image: postgres:15
    container_name: odoo18.2-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoodb18
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data:
