{
    "name": "Custom Email Marketing",
    "summary": "Override the Email Marketing menu with Companies and Contacts, and add real-time notification support.",
    "version": "1.0",
    "author": "Your Name / Company",
    "category": "Marketing",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "mass_mailing",
        "project",
        "web",
        "bus",
    ],
    "assets": {
        "web.assets_backend": [
            "custom_email_marketing/static/src/css/custom.css",
            "custom_email_marketing/static/src/js/chatter_filter.js",
            "custom_email_marketing/static/src/js/notification_init.js",
            "custom_email_marketing/static/src/js/notification_webclient.js",
            "custom_email_marketing/static/src/js/notification_widget.js",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "views/custom_menu_view.xml",
        "views/form_view_company.xml",
        "views/mailing_view_inherit.xml",
        "views/data/tech_stack_data.xml",
        "views/custom_send_email_template.xml",
        "views/discuss_view.xml",
        "views/project_task_view.xml",
        "views/send_task_email_wizard_view.xml",
        "wizards/project_task_move_views.xml",
    ],
    "installable": True,
    "application": True,
}
