{
    "name": "Custom Email Marketing",
    "summary": "Override the Email Marketing menu with Companies and Contacts, and add real-time notification support.",
    "version": "1.0",
    "author": "Your Name / Company",
    "category": "Marketing",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "mass_mailing",
        "project",
        "web",
        "bus",
    ],
    "assets": {
        "web.assets_backend": [
            "custom_email_marketing/static/src/css/custom.css",
            "custom_email_marketing/static/src/js/chatter_filter.js",
            "custom_email_marketing/static/src/js/chatter_button_order.js",
            # "custom_email_marketing/static/src/js/notification_popup.js",
            # "custom_email_marketing/static/src/js/kanban_record.js",
            # "custom_email_marketing/static/src/js/kanban_column_sort.js",
            "custom_email_marketing/static/src/js/mailing_list_kanban_header.js",
            "custom_email_marketing/static/src/js/kanban_header_cogmenu.js",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "views/custom_menu_view.xml",
        "views/form_view_company.xml",
        "views/mailing_view_inherit.xml",
        # "views/mailing_list_sort.xml",
        "views/data/tech_stack_data.xml",
        "views/custom_send_email_template.xml",
        "views/project_task_view.xml",
        "views/send_task_email_wizard_view.xml",
        "wizards/project_task_move_views.xml",
        # "views/mailing_mailtext_views.xml",
        "views/mailing_list_views_inherit.xml",
    ],
    "installable": True,
    "application": True,
}
